version: 1.0.{build}
branches:
  only:
  - iso_wg3
image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
platform:
  - x64
  - Win32

configuration: Release

install:
- cmd: git submodule update --init

before_build:
- cmd: >-
    md C:\projects\nfiq2\install

    cd C:\projects\nfiq2

    md build\Windows

    cd build\Windows

    cmake -A %PLATFORM% -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=C:\projects\nfiq2\install -DOPENCV_VERSION="3.4.8" C:\projects\nfiq2


build:
  project: C:\projects\nfiq2\build\Windows\NFIQ2_SUPERBUILD.sln
  verbosity: normal
  parallel: true
